#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-jsonpickle
Version  : 2.1.0
Release  : 26
URL      : https://files.pythonhosted.org/packages/35/0e/fe3ce0869add0213a1b45eef746cafb79ca45255a60ec918630c159e3490/jsonpickle-2.1.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/35/0e/fe3ce0869add0213a1b45eef746cafb79ca45255a60ec918630c159e3490/jsonpickle-2.1.0.tar.gz
Summary  : Python library for serializing any arbitrary object graph into JSON
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pypi-jsonpickle-license = %{version}-%{release}
Requires: pypi-jsonpickle-python = %{version}-%{release}
Requires: pypi-jsonpickle-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(importlib_metadata)
BuildRequires : pypi(py)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(setuptools_scm)
BuildRequires : pypi(wheel)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv

%description
.. image:: https://img.shields.io/pypi/v/jsonpickle.svg
:target: `PyPI link`_
.. image:: https://img.shields.io/pypi/pyversions/jsonpickle.svg
:target: `PyPI link`_

%package license
Summary: license components for the pypi-jsonpickle package.
Group: Default

%description license
license components for the pypi-jsonpickle package.


%package python
Summary: python components for the pypi-jsonpickle package.
Group: Default
Requires: pypi-jsonpickle-python3 = %{version}-%{release}

%description python
python components for the pypi-jsonpickle package.


%package python3
Summary: python3 components for the pypi-jsonpickle package.
Group: Default
Requires: python3-core
Provides: pypi(jsonpickle)
Requires: pypi(importlib_metadata)

%description python3
python3 components for the pypi-jsonpickle package.


%prep
%setup -q -n jsonpickle-2.1.0
cd %{_builddir}/jsonpickle-2.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1642179683
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-jsonpickle
cp %{_builddir}/jsonpickle-2.1.0/jsonpickleJS/LICENSE %{buildroot}/usr/share/package-licenses/pypi-jsonpickle/502b8fa73760ceab2e36965b01ec88535e230a33
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-jsonpickle/502b8fa73760ceab2e36965b01ec88535e230a33

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
